import type { DatosPDF } from 'src/types/dataType';

export const ejemploDatos: DatosPDF = {
  cliente: 'Juan Pérez',
  telefono: '555-1234',
  vehiculo: 'Toyota',
  tipo: 'Sedán',
  modelo: 'Corolla',
  año: '2020',
  placa: 'ABC-123',
  color: 'Rojo',
  km: '15000',
  vim: '1HGCM82633A004352',
  fechaIngreso: '23/07/2025',
  fechaSalida: '24/07/2025',
  tecnico: 'Luis Gómez',
  trabajo1: 'Cambio de aceite',
  trabajo2: 'Revisión de frenos',
  trabajo3: 'Alineación de dirección',
  trabajo4: 'Cambio de filtro de aire',
  trabajo5: 'Revisión de luces',
  trabajo6: 'Revisión de batería',
  trabajo7: 'Revisión de suspensión',
  trabajo8: 'Revisión de sistema de escape',
  trabajo9: 'Revisión de sistema de refrigeración',
  trabajo10: 'Revisión de sistema eléctrico',
  trabajo11: 'Inspección general',
  condiciones: [
    'El cliente se compromete a no dejar objetos de valor',
    'El cliente autoriza a el Taller efectuar los trabajos especificados',
  ],
  numeroOrden: '123456',
  ubicacion: 'Calle Francisco de Miranda esq. Gutierrez Guerra N° 1748',
  accesorios: [
    'GATA',
    'MANIVELA DE GATA',
    'LLAVE DE RUEDAS',
    'ESTUCHE DE HERRAMIENTAS',
    'TRIANGULO DE SEGURIDAD',
    'LLANTA DE REFACCION',
    'ESTINGUIDOR',
  ],
  componentes: [
    'TAPON DE ACEITE',
    'TAPON DE RADIADOR',
    'VARILLA DE ACEITE',
    'BATERIA (MCA)',
  ],
  exteriores: [
    'UNIDAD DE LUCES',
    '1/4 LUCES',
    'ANTENA',
    'ESPEJO LATERAL',
    'CRISTALES',
    'EMBLEMA',
    'LLANTAS (4)',
    'TAPON DE RUEDAS(4)',
    'MOLDURAS COMPLETAS',
    'TAPON DE GASOLINA',
    'CARROSERIA SIN GOLPES',
    'BOCINAS DE CLACSON',
    'LIMPIADORES (PLUMAS)',
  ],
  interiores: [
    'INSTRUMENTOS DE TABLERO',
    'CALEFACCION',
    'RADIO/TIPO',
    'BOCINAS',
    'ENCENDEDOR',
    'ESPEJO RETROVISOR',
    'CENICEROS',
    'CINTURONES',
    'BOTONES DE INTERIORES',
    'MANIJAS DE INTERIORES',
    'TAPETES ',
    'VESTIDURAS',
  ],
};
